// Generated by CoffeeScript 1.4.0
(function() {
  var http;

  http = require('http');

  http.createServer(function(req, res) {
    res.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    return res.end('Hello Node.js\n');
  }).listen(8124, "127.0.0.1");

  console.log('Server running at http://127.0.0.1:8124/');

}).call(this);
