// Generated by CoffeeScript 1.4.0
(function() {
  var $;

  $ = jQuery;

  $.fn.extend({
    detectCard: function(options) {
      var log, settings;
      settings = {
        debug: false
      };
      settings = $.extend(settings, options);
      log = function(msg) {
        if (settings.debug) {
          return typeof console !== "undefined" && console !== null ? console.log(msg) : void 0;
        }
      };
      return this.each(function() {
        var current_card_type, is_a_number, remove_spaces_from;
        current_card_type = 'none';
        $(this).data('card', current_card_type);
        $(this).after("<span class=\"card " + current_card_type + "\"/>");
        $(this).on('keyup', function(e) {
          var card_number, detected_card_type;
          detected_card_type = 'none';
          card_number = remove_spaces_from($(this).val());
          if (is_a_number(card_number)) {
            log("It's valid credit/debit card number");
            if (card_number.match(/^4/)) {
              detected_card_type = 'visa';
            }
            if (card_number.match(/^5[1-5]/)) {
              detected_card_type = 'mastercard';
            }
          }
          $(this).data('card', detected_card_type);
          $(".card." + current_card_type).text(detected_card_type);
          return current_card_type = detected_card_type;
        });
        remove_spaces_from = function(value) {
          return value.replace(/\s/g, '');
        };
        return is_a_number = function(value) {
          return value !== "" && !isNaN(value);
        };
      });
    }
  });

}).call(this);
