// Generated by CoffeeScript 1.4.0
(function() {
  var $;

  $ = jQuery;

  $.fn.extend({
    detectCard: function(options) {
      var log, settings;
      settings = {
        debug: false
      };
      settings = $.extend(settings, options);
      log = function(msg) {
        if (settings.debug) {
          return typeof console !== "undefined" && console !== null ? console.log(msg) : void 0;
        }
      };
      return this.each(function() {
        var current_card_type, get_card_number_from, get_card_type_to_show, is_a_number, remove_spaces_from, show_card_type_using, update_card_type;
        current_card_type = 'none';
        $(this).data('card', current_card_type);
        $(this).after("<span class=\"card " + current_card_type + "\"/>");
        $(this).on('keyup', function(e) {
          var card_number, detected_card_type;
          detected_card_type = 'none';
          card_number = get_card_number_from($(this).val());
          if (is_a_number(card_number)) {
            log("It's valid credit/debit card number");
            if (card_number.match(/^4/)) {
              detected_card_type = 'visa';
            }
            if (card_number.match(/^5[1-5]/)) {
              detected_card_type = 'mastercard';
            }
          }
          if (detected_card_type !== current_card_type) {
            update_card_type(this, detected_card_type, current_card_type);
            current_card_type = detected_card_type;
            return log("Current card type: " + current_card_type);
          }
        });
        update_card_type = function(card_element, detected_type, current_type) {
          $(card_element).data('card', detected_type);
          $(".card." + current_type).removeClass(current_type).addClass(detected_type);
          return show_card_type_using(detected_type);
        };
        show_card_type_using = function(type) {
          return $(".card." + type).text(get_card_type_to_show(type));
        };
        get_card_type_to_show = function(card_type) {
          if (card_type !== 'none') {
            return card_type;
          } else {
            return '';
          }
        };
        get_card_number_from = function(card_input) {
          return remove_spaces_from(card_input);
        };
        remove_spaces_from = function(value) {
          return value.replace(/\s/g, '');
        };
        return is_a_number = function(value) {
          return value !== "" && !isNaN(value);
        };
      });
    }
  });

}).call(this);
